### ISSUE TITLE
GEOQuery fails with "cannot open the connection"

### ISSUE THREAD

**Issue by oneillkza** [sblanck/smagexp#1]
Hi

I've run SMAGEXP using the Docker image (per the instructions in the readme), but when I try to download data from GEO using GEOQuery, I get the following error:

```
Fatal error: Exit code 1 ()
https://ftp.ncbi.nlm.nih.gov/geo/series/GSE3nnn/GSE3524/matrix/
OK
Found 2 file(s)
/geo/series/GSE3nnn/GSE3524/
Error in file(con, "r") : cannot open the connection
Calls: getGEO ... getAndParseGSEMatrices -> parseGSEMatrix ->
``` 

I thought maybe this was due to the container being read-only, so I tried running it with the local data option, ie:

```
docker run -d -p 8080:80 -v /home/kieran/galaxy_storage/:/export/ sblanck/galaxy-smagexp
```

But I get the same error message.

**Comment by sblanck** [comment]
Hi,
It looks like this problem was related with the version of GEOquery. I've updated GEOquery into the docker image and pushed it to the docker hub repository

To get the new docker image run : `docker pull sblanck/galaxy-smagexp`
And then, run it with  `docker run -d -p 8080:80 -p 8021:21 -p 8022:22 sblanck/galaxy-smagexp`.
